### PR TITLE
Generalized Unigram support, T5

### PR DESCRIPTION
**Pull request by pcuenca**

### CODE REVIEW

**Comment by hassanzadeh** [comment]
Hey Guys,
Thanks for your support,
May I ask what is your estimated time for this to be ready?

Best

**Review by hassanzadeh — COMMENTED** [review]
Is this really going to work for T5? T5Tokenizer is based on Sentence Piece not BPE.

**Comment by hassanzadeh** [comment]
I see thanks for the quick response. Is it done or it is still in progress?
When do you think you will merge?

**Comment by pcuenca** [comment]
This is ready to test / review now.

**Comment by pcuenca** [comment]
Merging now. @hassanzadeh please, do let me know if you see anything unusual.

**Pull request merged**
