### PR TITLE
Chat templates by @maiqingqiang

### PR DESCRIPTION
**Pull request by pcuenca**
Continuation of #77 by @maiqingqiang, with support for `addSpecialTokens` to mimic the reference tokenizers implementation.

### CODE REVIEW

**Comment by maiqingqiang** [comment]
Nice 👍

**Comment by maiqingqiang** [comment]
Hi @pcuenca! Can you help review https://github.com/maiqingqiang/Jinja? This repo already meets most of the Jinja Chat Templates. Also, you're invited to be a Jinja Collaborator.🤝🏻

**Comment by maiqingqiang** [comment]
> Hi @pcuenca! Can you help review https://github.com/maiqingqiang/Jinja? This repo already meets most of the Jinja Chat Templates. Also, you're invited to be a Jinja Collaborator.🤝🏻

https://github.com/maiqingqiang/Jinja/invitations

**Comment by pcuenca** [comment]
> > Hi @pcuenca! Can you help review https://github.com/maiqingqiang/Jinja? This repo already meets most of the Jinja Chat Templates. Also, you're invited to be a Jinja Collaborator.🤝🏻

Thank you @maiqingqiang! I'm travelling and a bit slow to respond, I'll be happy to take a look next week!

**Comment by maiqingqiang** [comment]
> > > Hi @pcuenca! Can you help review https://github.com/maiqingqiang/Jinja? This repo already meets most of the Jinja Chat Templates. Also, you're invited to be a Jinja Collaborator.🤝🏻
> 
> Thank you @maiqingqiang! I'm travelling and a bit slow to respond, I'll be happy to take a look next week!

Thank you @pcuenca !🍻

**Comment by pcuenca** [comment]
Thoughts on merging this @FL33TW00D, @vaibhavs10 ?

When I'm back at my desk I'm planning to take a closer look at the template engine that @maiqingqiang created, but it works fine already. Some potential changes we would want to do before merging are:

- Add some additional tests, currently we are just testing Mistral without a system prompt.
- Remove the padding logic, as we are not using it anywhere else in the project. It might make more sense to address it as another PR globally for the project. But we can still keep it there if that's easier.

Any other thoughts or details?

**Comment by mzbac** [comment]
Looking forward to this feature, thanks for the great work 🚀

**Review by Vaibhavs10 — COMMENTED** [review]
Sorry I missed this earlier:

> Add some additional tests, currently we are just testing Mistral without a system prompt.
> Remove the padding logic, as we are not using it anywhere else in the project. It might make more sense to address it as another PR globally for the project. But we can still keep it there if that's easier.

Nicely done (from my *very* limited swift knowledge! I think a few tests and we should merge it and follow up all other updates to a new PR.

**Comment by maiqingqiang** [comment]
Currently, I am developing a MacOS App - ChatMLX based on this PR. Looking forward to the merge of this PR.
https://github.com/maiqingqiang/ChatMLX/releases/tag/beta

**Comment by pcuenca** [comment]
Hi @maiqingqiang! I'm going to try to merge to unblock you, sorry for the delay! Do you need the padding logic? There are some conflicts that would be easier to resolve if we can remove it and add in a different PR.

**Comment by maiqingqiang** [comment]
> Hi @maiqingqiang! I'm going to try to merge to unblock you, sorry for the delay! Do you need the padding logic? There are some conflicts that would be easier to resolve if we can remove it and add in a different PR.

Hi @pcuenca . Thank! I don't need the padding logic. You can remove  it.

**Comment by pcuenca** [comment]
Tests pass, merging now!

Thanks a lot for this amazing contribution, @maiqingqiang, and also for your patience! 🙌 We can add tests and get back to supporting padding in a future PR :)

**Comment by maiqingqiang** [comment]
Thank you very much 🤝🏻🤝🏻 @pcuenca

**Comment by maiqingqiang** [comment]
Hi @pcuenca, could you please tag a new release for swift-transformers?

**Comment by pcuenca** [comment]
https://github.com/huggingface/swift-transformers/releases/tag/0.1.10

**Pull request merged**
